# 线上配置文件
# @author <a href="https://github.com/lhccong">程序员聪</a>
#  
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456

  flyway:
    enabled: true  # 启用flyway
    baseline-on-migrate: true  # 当数据库非空且无flyway元数据表时，自动初始化
    locations: classpath:db/migration  # 脚本位置
    validate-on-migrate: true  # 迁移时校验脚本
    out-of-order: false  # 是否允许无序迁移(生产环境建议false)
    clean-disabled: true  # 禁用clean命令(生产环境必须为true)

  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
